server:
  port: 8080

#debug: true
#
##Turn logging to WARN for org.*
logging:
  level:
      org: WARN
#
#      #proxy, security-open
#      spring:
#        profiles:
#            active: security,proxy

