---
app:
  greeting: hello, world (git)
  encrypted-greeting: '{cipher}{key:robkey}AQAr92Yp+pR5OqxpT87brl6ERtzrhtQq+rh1FA6q5ie+uxLPG5lE3zYBHbzY1sOVwq6xApDbTatbNmuqrYMkA9PJfFgnf4g7/Ioad3NRbugZcU7c3FAkHVZLxn+oO/AOZyaW/OLUoph++JbOqgRPXDxlUzMM6FVbM6Bj1gX3ZsUmW0u6bOVktgj9X/fqKPj6QAJcMZoppWKmMLMyJ57A+C/JQl7JEIEXWlp2AqAqhCn3nlFyRNed1gx7xX6kC6wKbRM3CNcHC+tkWP7vLoHqWia3uIwhUX8U0DvDJJTSvNQgYzuc2AbXaAtb60Yowkze71vqtDMSLdWiaXIT34dU1ZuKJ5bycgf7VihW0dEd+sIsLL8iJq+BVFmYlC9NEm3IL8gbkh5/M7g9yKwxzAq/xcjWtlUiF0n66v9CyqRd5OxKeQ=='

security:
  basic:
    enabled: false
management:
  security:
    enabled: false


---
spring:
  profiles: boeing
app:
  greeting: hello, world (git boeing profile)
