---
app:
  greeting: hello, world (git)
  encrypted-greeting: '{cipher}AQAP4soKifdsxiLMbV3aNCS3a0f0CaPNPgrI3WT+hk0eOdmMQJ089hadUwCs90X5kWmMQLgzXRnqQICwtHuALRWTH2ViZVmWMehNJLrjd7G7Jf+AS7C7CuFszGFlPfAsTyv8j8M+iCdyoDO5DgeO2YQthUiivzMxRPSfXDzhzw26MExAGhW4kcoFPwmrgG+jaBVCE11VdEStsgX19bo6AQqoPm+ODni0+9lBfDpq5sLxtifIoMB2LIFvPUInCpe73y4tUINa7WyIA5F7BxpPo0mhlymyrhsl05CJn9Vq5IcBERRqcmKu1TadRJF6EUJE1SsxHECzLr1sqhLY1aAXH+1SdiVpXep1GJ0XlHscZ38ZF3QValHyjELHn4Lf+bUv2sBUnYJ3tn19oXTABjtCeGQW2RPL7eFtl02rGnJgMwJvqA=='
---
spring:
  profiles: boeing
app:
  greeting: hello, world (git boeing profile)
