---
app:
  greeting: hello, world (git)
  encrypted-greeting: '{cipher}AQBv+QekpzuVNAGjTSQ0FZaqNpEnrPn0RCjC40eAV6Pq01Ecy5NKc6MXvk5BK5MpRZMyutuWTapSwKeOBqj5nPQRJwI+Y07MpD5buduAsfmL8DVwl9arnZi8vjLtoVLlVBEZMwKgL4T35YYkDJcqKtLoPqdBjinbtmBXysFL9F0vPVfsv6iQ/JZ3mkxBEWOqqzTz9UY3p9YhUR5xo8bJ9TwIrkmkHMDV+RcDbtlt1ucdDlo9i9UrW9SKlbcltPG1cxaoPa/IIZfUNLM99zpOkYuXy1nvLtQYvOfGWAP4K9bhg7fc8Raga2UJaBgXW/7i3H6Wr5jun2NeqTWTOqUhLrYe+UA4DQGPS+XlRv/pnob12/sPzd7Hvu7EmD9plggayVUr+XcHQMxR/2xaAj1wgwwoG4Op93W6l5ZYG2xsW4M7+w=='
---
spring:
  profiles: boeing
app:
  greeting: hello, world (git boeing profile)
